apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-app
        image: k8s-lab-demo-gateway:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
